### ISSUE TITLE
uninitialized constant Mathjax_Renderer

### ISSUE THREAD

**Issue by Akanoa** [sashee/mathjax-renderer#1]
Hello,

I'm totally noob in ruby and when I try to launch my code a "NameError - uninitialized constant Mathjax_Renderer:" exception is thrown. I guess I have to add a "require" directive but I don't manage to find it.

Thanks.

**Comment by sashee** [comment]
Hi,

you might need to use _require 'mathjax_renderer/renderer'_. Also make sure you have the renderer in your Gemfile, so that the files are actually present on your system.

As per usage, you can refer to the feature definitions: 
- https://github.com/sashee/mathjax-renderer/blob/master/features/support/env.rb
- https://github.com/sashee/mathjax-renderer/blob/master/features/step_definitions/html_steps.rb
- https://github.com/sashee/mathjax-renderer/blob/master/features/step_definitions/image_steps.rb

Hope it helps
